node {
    checkout scm
    docker.image('maven:3.9.2-amazoncorretto-8-debian-bullseye').inside("-v /root/.m2:/root/.m2")
    stage('Build') {
        sh 'echo "Hello Build"'
    }
    stage('Test') {
            sh 'echo "Hello Test"'
    }
    stage('Deliver') {
            sh 'echo "Hello deliver"'
    }
}
