node {
    stage('Build') {
        checkout scm
        docker.image('maven:3.9.2-amazoncorretto-8-debian-bullseye')
        sh 'mvn -B -DskipTests clean package'
        sh 'echo "Hello Build"'
    }
    stage('Test') {
            sh 'echo "Hello Test"'

    }
    stage('Deliver') {
            sh 'echo "Hello deliver"'
    }
}
